name: CI

on:
  push:
    branches:
      - main

jobs:
  linting:
    name: Python Linting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-versions: ['3.10', '3.11', '3.12']

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 app.py
          

  testing:
    name: unit-testing
    needs: linting #this line added to run this testing job sequential, if we remove this line both jobs will run parallel
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run unit test
        run: |
          python -m unittest discover